# -*- coding: utf-8 -*-
"""hasyim_citradigital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VI2aoW2-Fzu_Yb3oUEgxX3r8V7fR1uwa
"""

import cv2 as cv
import numpy as np
from google.colab import files
from google.colab.patches import cv2_imshow
import ipywidgets as widgets
from IPython.display import display, clear_output
import io
from PIL import Image

# Variabel global untuk menyimpan gambar
img_original = None
img_processed = None

# UI untuk Upload
upload_btn = widgets.FileUpload(accept='image/*', multiple=False)
output = widgets.Output()

def on_upload_change(change):
    global img_original
    with output:
        clear_output()
        if not upload_btn.value:
            return

        # Mengambil data gambar
        uploaded_file = list(upload_btn.value.values())[0]
        content = uploaded_file['content']

        # Konversi ke format OpenCV
        nparr = np.frombuffer(content, np.uint8)
        img_original = cv.imdecode(nparr, cv.IMREAD_COLOR)

        print("Gambar berhasil diunggah!")
        cv2_imshow(img_original)

upload_btn.observe(on_upload_change, names='value')

print("1. Silakan Unggah Gambar Anda:")
display(upload_btn, output)

import cv2 as cv
import numpy as np
from google.colab.patches import cv2_imshow
import ipywidgets as widgets
from IPython.display import display, clear_output

# Variabel global
img_dash = None

# Widgets untuk UI Utama
menu_opsi = widgets.Dropdown(
    options=[
        ('Pilih Operasi', 0),
        ('Brightness & Contrast', 1),
        ('Image Blending', 2),
        ('Grayscale', 3),
        ('Thresholding', 4),
        ('Negasi (Citra Negatif)', 5)
    ],
    value=0,
    description='Operasi:',
)

# Widgets untuk kontrol spesifik
bright_slider = widgets.IntSlider(value=0, min=-100, max=100, description='Brightness')
contrast_slider = widgets.FloatSlider(value=1.0, min=0.5, max=3.0, step=0.1, description='Contrast')
blend_slider = widgets.FloatSlider(value=0.5, min=0.0, max=1.0, step=0.1, description='Alpha')
thresh_slider = widgets.IntSlider(value=127, min=0, max=255, description='Threshold')

# Tombol Eksekusi
btn_proses = widgets.Button(description="Jalankan Operasi", button_style='success')
output_dash = widgets.Output()
container_controls = widgets.VBox([])

def update_controls(*args):
    if menu_opsi.value == 1:
        container_controls.children = [bright_slider, contrast_slider]
    elif menu_opsi.value == 2:
        container_controls.children = [blend_slider]
    elif menu_opsi.value == 4:
        container_controls.children = [thresh_slider]
    else:
        container_controls.children = []

menu_opsi.observe(update_controls, 'value')

def proses_gambar(b):
    global img_original
    with output_dash:
        clear_output()
        if img_original is None:
            print("Silakan unggah gambar di sel paling atas terlebih dahulu!")
            return

        res = None
        if menu_opsi.value == 1:
            res = cv.convertScaleAbs(img_original, alpha=contrast_slider.value, beta=bright_slider.value)
            print("Hasil Brightness & Contrast:")
        elif menu_opsi.value == 2:
            img2 = np.zeros_like(img_original)
            img2[:] = (255, 150, 0)
            res = cv.addWeighted(img_original, blend_slider.value, img2, 1 - blend_slider.value, 0)
            print("Hasil Blending dengan Warna:")
        elif menu_opsi.value == 3:
            gray = cv.cvtColor(img_original, cv.COLOR_BGR2GRAY)
            res = cv.cvtColor(gray, cv.COLOR_GRAY2BGR)
            print("Hasil Grayscale:")
        elif menu_opsi.value == 4:
            gray = cv.cvtColor(img_original, cv.COLOR_BGR2GRAY)
            _, thresh = cv.threshold(gray, thresh_slider.value, 255, cv.THRESH_BINARY)
            res = cv.cvtColor(thresh, cv.COLOR_GRAY2BGR)
            print(f"Hasil Thresholding (Nilai: {thresh_slider.value}):")
        elif menu_opsi.value == 5:
            res = cv.bitwise_not(img_original)
            print("Hasil Negasi (Citra Negatif):")
        else:
            print("Pilih operasi terlebih dahulu.")
            return

        if res is not None:
            cv2_imshow(np.hstack((img_original, res)))

btn_proses.on_click(proses_gambar)

print("--- PANEL KENDALI CITRA TERPADU ---")
display(menu_opsi, container_controls, btn_proses, output_dash)

print("2. Operasi Brightness & Contrast")

# Widget Input
bright_slider = widgets.IntSlider(value=0, min=-100, max=100, description='Brightness:')
contrast_slider = widgets.FloatSlider(value=1.0, min=0.5, max=3.0, step=0.1, description='Contrast:')
apply_btn = widgets.Button(description="Terapkan Perubahan", button_style='primary')
output_bc = widgets.Output()

def apply_brightness_contrast(b):
    global img_original, img_processed
    with output_bc:
        clear_output()
        if img_original is None:
            print("Silakan unggah gambar di sel pertama terlebih dahulu!")
            return

        # Rumus: g(x) = alpha * f(x) + beta
        alpha = contrast_slider.value
        beta = bright_slider.value
        img_processed = cv.convertScaleAbs(img_original, alpha=alpha, beta=beta)

        print(f"Hasil (Contrast: {alpha}, Brightness: {beta}):")
        # Menampilkan Sebelum dan Sesudah
        combined = np.hstack((img_original, img_processed))
        cv2_imshow(combined)

apply_btn.on_click(apply_brightness_contrast)
display(bright_slider, contrast_slider, apply_btn, output_bc)

print("3. Operasi Penggabungan (Image Blending)")

blend_slider = widgets.FloatSlider(value=0.5, min=0.0, max=1.0, step=0.1, description='Alpha Blend:')
blend_btn = widgets.Button(description="Gabungkan Gambar", button_style='success')
output_blend = widgets.Output()

def apply_blending(b):
    global img_original
    with output_blend:
        clear_output()
        if img_original is None:
            print("Silakan unggah gambar di sel pertama!")
            return

        # Buat gambar kedua (gradient warna) dengan ukuran yang sama
        h, w, c = img_original.shape
        img2 = np.zeros((h, w, c), np.uint8)
        img2[:] = (255, 100, 0) # Warna solid sebagai contoh

        alpha = blend_slider.value
        beta = 1.0 - alpha
        dst = cv.addWeighted(img_original, alpha, img2, beta, 0.0)

        print("Kiri: Asli | Kanan: Hasil Gabungan dengan Warna Solid")
        cv2_imshow(np.hstack((img_original, dst)))

blend_btn.on_click(apply_blending)
display(blend_slider, blend_btn, output_blend)

print("4. Operasi Grayscale (Hitam Putih)")

gray_btn = widgets.Button(description="Ubah ke Grayscale", button_style='info')
output_gray = widgets.Output()

def make_grayscale(b):
    global img_original
    with output_gray:
        clear_output()
        if img_original is None:
            print("Unggah gambar terlebih dahulu!")
            return

        gray = cv.cvtColor(img_original, cv.COLOR_BGR2GRAY)
        # Konversi balik ke BGR hanya untuk tampilan hstack
        gray_bgr = cv.cvtColor(gray, cv.COLOR_GRAY2BGR)

        print("Hasil Grayscale:")
        cv2_imshow(np.hstack((img_original, gray_bgr)))

gray_btn.on_click(make_grayscale)
display(gray_btn, output_gray)



import cv2 as cv
from google.colab.patches import cv2_imshow

# operasi aras lokal
img = cv.imread('/content/photo_2026-02-01_21-22-53.jpg')
mean_filter = cv.blur(img, (50,50))

hasil = cv.hconcat([img, mean_filter])
cv2_imshow(hasil)

# operasi flipping
flip_horizontal = cv.flip(img, 1)
flip_vertical = cv.flip(img, 0)

hasil = cv.hconcat([img, flip_horizontal, flip_vertical])
cv2_imshow(hasil)

# operasi rotasi
(h, w) = img.shape[:2]

center = (w // 2, h // 2)

rotasi = cv.getRotationMatrix2D(center, 45, 1.0)
hasil_rotasi = cv.warpAffine(img, rotasi, (w, h))

hasil = cv.hconcat([img, hasil_rotasi])
cv2_imshow(hasil)

# Operasi Pemotongan (Cropping)
crop = img[100:300, 200:400]
crop_resize = cv.resize(crop, (img.shape[1], img.shape[0]))

cv2_imshow(crop)

# Operasi Scaling/zooming
scale_up = cv.resize(img, None, fx=1.5, fy=1.5)
scale_down = cv.resize(img, None, fx=0.5, fy=0.5)

cv2_imshow(img)
cv2_imshow(scale_up)
cv2_imshow(scale_down)

# Operasi Aras Lokal
import cv2 as cv
from google.colab.patches import cv2_imshow

# operasi aras lokal
img = cv.imread('/content/Screenshot 2026-04-30 091303.png')

# Menambahkan Efek blur pada gambar
mean_filter = cv.blur(img, (5,5))

# Menampilkan hasil gabungan dengan efek blur
hasil = cv.hconcat([img, mean_filter])
cv2_imshow(hasil)

# operasi flipping
import cv2 as cv
from google.colab.patches import cv2_imshow


flip_horizontal = cv.flip(img, 1)
flip_vertical = cv.flip(img, 0)

hasil = cv.hconcat([img, flip_horizontal, flip_vertical])
cv2_imshow(hasil)

# operasi Rotation
import cv2 as cv
from google.colab.patches import cv2_imshow

img = cv.imread('/content/photo_2026-02-01_21-22-53.jpg')
center = (w // 2, h // 2)

rotasi = cv.getRotationMatrix2D(center, 45, 1.0)
hasil_rotasi = cv.warpAffine(img, rotasi, (w, h))

hasil = cv.hconcat([img, hasil_rotasi])
cv2_imshow(hasil)

# Operasi Cropping
import cv2 as cv
from google.colab.patches import cv2_imshow

img = cv.imread('/content/photo_2026-02-01_21-22-53.jpg')


crop = img[100:300, 200:400]

crop_resize = cv.resize(crop, (img.shape[1], img.shape[0]))

cv2_imshow(crop)

# Operasi Scalling/ Zoom
import cv2 as cv
from google.colab.patches import cv2_imshow


img = cv.imread('/content/photo_2026-02-01_21-22-53.jpg')
scale_up = cv.resize(img, None, fx=1.5, fy=1.5)
scale_down = cv.resize(img, None, fx=0.5, fy=0.5)

cv2_imshow(img)
cv2_imshow(scale_up)
cv2_imshow(scale_down)

import cv2
import matplotlib.pyplot as plt

image = cv2.imread('/content/DSC04915.JPG', 0)

#Hitung Histogram
hist = cv2.calcHist([image], [0], None, [256], [0, 256])

plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
plt.imshow(image, cmap='gray')
plt.title('Original Image')
plt.axis('off')

plt.subplot(1,2,2)
plt.plot(hist, color='black')
plt.title('Histogram')
plt.xlim([0, 256])

plt.show()

import cv2 as cv
import numpy as np
from google.colab.patches import cv2_imshow

img = cv.imread('/content/0c85316c-b12f-4db2-962e-a3bd033649d6.jpg', 0)

kernel = np.ones((3,3), np.float32)/9
hasil = cv.filter2D(img, -1, kernel)

cv2_imshow(img)
cv2_imshow(hasil)

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

#Membaca gambar greyskale
img = cv2.imread('/content/Mata_kucing.jpg', 0)

#kernel
kernel = np.array([[-1, -1, -1],
                   [-1, 9, -1],
                   [-1, -1, -1]])

hasil = cv2.filter2D(img, -1, kernel)

#Menampilkan gambar asli dan hasil
cv2_imshow(img)
cv2_imshow(hasil)

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

#Membaca gambar greyskale
img = cv2.imread('/content/Mata_kucing.jpg', 0)
cv2_imshow(img)

quantized = img // 64
quantized_display = quantized * 64
print("Hasil Pemampatan (4 derajat keabuan")

#RGB ke XYZ
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

#Membaca citra
img = cv2.imread('/content/photo_2026-06-04_09-34-50.jpg')

#OpenCV membaca dalam format BGR
B = img[:, :, 0].astype(float)
G = img[:, :, 1].astype(float)
R = img[:, :, 2].astype(float)

#Transformasi RGB ke XYZ
X = 0.490*R + 0.310*G + 0.200*B
Y = 0.177*R + 0.813*G + 0.010*B
Z = 0.010*G + 0.990*B

#Membatasi nilai maksimum 255
X = np.clip(X, 0, 255).astype(np.uint8)
Y = np.clip(Y, 0, 255).astype(np.uint8)
Z = np.clip(Z, 0, 255).astype(np.uint8)

#Menampilkan hasil
cv2_imshow(X)
cv2_imshow(Y)
cv2_imshow(Z)

#XYZ ke RGB
R2 = 2.365*X - 0.896*Y - 0.468*Z
G2 = -0.515*X + 1.425*Y + 0.088*Z
B2 = 0.005*X - 0.014*Y + 1.009*Z

#Batasi ke rentang 0-255
R2 = np.clip(R2, 0, 255).astype(np.uint8)
G2 = np.clip(G2, 0, 255).astype(np.uint8)
B2 = np.clip(B2, 0, 255).astype(np.uint8)

#Menampilkan hasil
hasil_rgb = cv2.merge([B2, G2, R2])
cv2_imshow(hasil_rgb)

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

#Membaca Gambar
img = cv2.imread('/content/photo_2026-06-04_09-34-50.jpg')

#OpenCV menggunakan BGR
B = img[:, :, 0].astype(float)
G = img[:, :, 1].astype(float)
R = img[:, :, 2].astype(float)

#RGB -> CMY
C = 255 - R
M = 255 - G
Y = 255 - B

#Menentukan K
K = np.minimum(np.minimum(C, M), Y)

#Mengurangi K dari C, M, Y
C = C - K
M = M - K
Y = Y - K

#Mengembalikan CMYK menjadi RGB
C2 = C + K
M2 = M + K
Y2 = Y + K

#Pastikan tidak melebihi 255
C2 = np.clip(C2, 0, 255)
M2 = np.clip(M2, 0, 255)
Y2  = np.clip(Y2, 0, 255)

R2 = 255 - C2
G2 = 255 - M2
B2 = 255 - Y2

#Gabungkan kembali
rgb_hasil = cv2.merge([
    B2.astype(np.uint8),
    G2.astype(np.uint8),
    R2.astype(np.uint8)
])

print("RGB ke CMYK")
cv2_imshow(rgb_hasil)

#Menampilkan Hasil
print("Channel Cyan")
cv2_imshow(C)
print("Channel Magenta")
cv2_imshow(M)
print("Channel Yellow")
cv2_imshow(Y)
print("Channel Black")
cv2_imshow(K)

